version: 1
force:
  major: 1
  existing: false
  strict: false
wording:
  patch:
    - update
    - initial
    - fix
  minor:
    - change
    - improve
  major:
    - breaking
  release:
    - release-candidate